### ISSUE TITLE
`bunch prune` is too aggressive

### ISSUE THREAD

**Issue by tamird** [dkulchenko/bunch#13]
`bunch prune` seems not to handle sub-packages.

For instance, my project depends on `github.com/cockroachdb/cockroach/util`, but `bunch prune` only sees the top-level `github.com/cockroachdb/cockroach`, which is not used directly. `bunch prune` then removes `github.com/cockroachdb/cockroach`, which means I don't have `github.com/cockroachdb/cockroach/util` anymore, and that's Bad.

**Comment by dkulchenko** [comment]
Completely retooled the way `bunch prune` works in 404d8a4, this is now fixed.

**Comment by tamird** [comment]
Looks good, thanks!
