### ISSUE TITLE
`bunch prune` doesn't clean up correctly

### ISSUE THREAD

**Issue by tamird** [dkulchenko/bunch#14]
In my project's `Bunchfile`:
```
google.golang.org/api/compute/v1
google.golang.org/api/googleapi
google.golang.org/api/resourceviews/v1beta2
```

Due to `bunch prune` bugs described in #13, all these packages are deemed unused, and are removed, along with the repo's `.git`. However, `.vendor/src/google.golang.org/api/googleapi/` is left alone for some reason, but since the `.git` is gone, the next attempt to `bunch install` fails on `go get -d google.golang.org/api/compute/v1` with:
```
google.golang.org/api/compute/v1: /Users/tamird/src/go/src/github.com/cockroachdb/cockroach-prod/.vendor/src/google.golang.org/api exists but /Users/tamird/src/go/src/github.com/cockroachdb/cockroach-prod/.vendor/src/google.golang.org/api/.git does not - stale checkout?
```

**Comment by dkulchenko** [comment]
Completely retooled the way `bunch prune` works in 404d8a4, this is now fixed.
