### ISSUE TITLE
`bunch lock` doesn't emit refs for non-dependencies (e.g. commands)

### ISSUE THREAD

**Issue by tamird** [dkulchenko/bunch#16]
My project uses [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) as an executable (meaning no file depends on it) and running `bunch lock` emits the following into `Bunchfile.lock`:
```
"golang.org/x/tools/cmd/goimports": "",
```
Is this behaviour expected? Why?

**Comment by dkulchenko** [comment]
bunch uses go's provided deps list to get the list of packages to use during 'bunch generate'.

Does running `go list --json .` in your package directory have goimports in the list? If so, there's a dependency on it somewhere, or perhaps it's a subdependency for one of your deps.

**Comment by tamird** [comment]
No, goimports is not in the list - I manually added it to the `Bunchfile` with `bunch install --save golang.org/x/tools/cmd/goimport`. The surprising part is that `bunch lock` doesn't actually lock goimport.

**Comment by dkulchenko** [comment]
Ah, I see. That's a bug - looking into it.
