### ISSUE TITLE
support for private github repos

### ISSUE THREAD

**Issue by tve** [dkulchenko/bunch#21]
When working with a private github repo bunch fails because it tries to use the https repo URL instead of the git one. The result is that it asks for a username/password instead of using the user's SSH key. Or am I missing some trick?

**Comment by dkulchenko** [comment]
This is `go get` behavior, which bunch uses internally. Discussed here: https://github.com/golang/go/issues/9697, the workaround would be running `git config --global url."git@github.com:".insteadOf "https://github.com/"`.
