### ISSUE TITLE
non-repo packages are not versioned properly (unknown repo type)

### ISSUE THREAD

**Issue by MBerhault** [dkulchenko/bunch#22]
We're specifying packages that are not repos, and this seems to be causing problems for bunch.

Sample Bunchfile.lock line:
```
"github.com/awslabs/aws-sdk-go/service/ec2": "deaa78b60cfd55045252c52f4f7840c6d697c491",
```

bunch install output: (the interesting bit is at the end of the "setting version" line)
```
installing github.com/awslabs/aws-sdk-go/service/ec2 ... 
  - setting version of github.com/awslabs/aws-sdk-go/service/ec2 to  (resolved as deaa78b60cfd55045252c52f4f7840c6d697c491) ... skipped, unknown repo type
  - building package github.com/awslabs/aws-sdk-go/service/ec2 ... done
  - installing package github.com/awslabs/aws-sdk-go/service/ec2 ... done
successfully installed github.com/awslabs/aws-sdk-go/service/ec2
```

We're doing this a lot ([full file](https://github.com/cockroachdb/cockroach-prod/blob/master/Bunchfile.lock)), especially for things like the AWS SDK that have many parts we don't care about.

Please let me know if you need further information.

**Comment by MBerhault** [comment]
CC: @tamird

**Comment by MBerhault** [comment]
I changed:
```
packageDir := path.Join(gopath, "src", getRealRepoPath(repo))
```
to:
```
packageDir, err := getPackageRootDir(repo)
if err != nil
...
```

And that did it. Not sure what the ramifications might be though.

**Comment by tamird** [comment]
Discussed in person: we think the solution here is to track the repo in Bunchfile.lock, not the full package path.

**Comment by dkulchenko** [comment]
@MBerhault, yep, that is the fix (with one minor tweak). d07244f should do it.
