### ISSUE TITLE
bunch prune deletes .git repo

### ISSUE THREAD

**Issue by jjude** [dkulchenko/bunch#28]
When I issue `bunch prune`, it deletes .git repository directory.

**Comment by dkulchenko** [comment]
> When I issue bunch prune, it deletes .git repository directory.

@jjude, which .git repository does it delete? What's your Bunchfile/.vendor directory setup?

**Comment by jjude** [comment]
1. It delete .git of my app
2. directory setup     
myapp     
    |_ .git     
    |_ .vendor     
    |_ Bunchfile

**Comment by dkulchenko** [comment]
Can't repro:

```
daniilk:~/test ∞ ls -a
.         ..        .git      .vendor   Bunchfile
daniilk:~/test ∞ bunch prune
daniilk:~/test ∞ ls -a
.         ..        .git      .vendor   Bunchfile
daniilk:~/test ∞
```

What's your Bunchfile contents?
