### ISSUE TITLE
bunch install gosync fails

### ISSUE THREAD

**Issue by jjude** [dkulchenko/bunch#30]
This may not be an issue with bunch itself (I don't know).

When I issue `bunch install github.com/brettweavnet/gosync`, it fails with this output:
```
installing github.com/brettweavnet/gosync ... 2015/06/01 10:59:02 failed installing packages: failed building package github.com/brettweavnet/gosync, error: go install github.com/brettweavnet/gosync: build output "gosync" already exists and is a directory
, output: %!s(MISSING): exit status 1 [exit status 1 github.com/dkulchenko/bunch/packages.go:234: failed building package github.com/brettweavnet/gosync, error: go install github.com/brettweavnet/gosync: build output "gosync" already exists and is a directory
, output: %!s(MISSING) github.com/dkulchenko/bunch/packages.go:633: ]
```

I deleted .vendor folder & tried    
I deleted all directories named gosync (in src, pkg, bin folders) and tried   
I updated bunch and tried (bunch -v = 0.6)

Still I get the same error. As I said, I don't know if it is an error with bunch itself. But I don't know how to go about troubleshooting it. Any help?

**Comment by dkulchenko** [comment]
gosync is not go-get compatible (i.e. has its own build process), so will not work with bunch.

See https://github.com/brettweavnet/gosync#installation for gosync's install instructions.
