### ISSUE TITLE
Error in installing yaml.v2

### ISSUE THREAD

**Issue by jjude** [dkulchenko/bunch#8]
`bunch install gopkg.in/yaml.v2 —save` 

throws the below error:

`failed installing packages: failed cloning repo for package github.com/gopkg.in/yaml.v2: exit status 1`

I didn't face any issue installing it via goop though.

**Comment by dkulchenko** [comment]
Thanks @jjude! Fixed in 4655237, part of the about-to-be-released v0.3.
